In [1]:
import numpy as np
import pandas as pd

In [2]:
movie = pd.read_csv('tmdb_5000_movies.csv')

In [3]:
credit = pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movie.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [5]:
credit.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
movie = movie.merge(credit,on='title')     ## title ke according merge hogya hai

In [7]:
movie.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
## now we are going to remove that columns which are not useful for analysis
# genres are important column, id is important as at the end will gonna fetch the poster, keywords, take title not original_title as title will be in english only, overview   
# original_language highly imbalanced hai toh may be gddbdd kerskta hai
## will not take numerical column as it is not consistent with our workflow
# tag line is textual, overall sai nhi hota kabhi kabhi , as we alrady taken overview so not that much worthy

In [9]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [10]:
#release_data can we usefull but its numerical
#cast, crew usefull

In [11]:
#genres
#id
#keywords
#overview
#title
##cast
#crew
movie = movie[['movie_id','title','keywords','genres','cast','crew','overview']]

In [12]:
movie.head()

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,49529,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca..."

In [13]:
movie.isnull().sum()

movie_id    0
title       0
keywords    0
genres      0
cast        0
crew        0
overview    3
dtype: int64

In [14]:
movie.dropna(inplace= True)

In [15]:
movie.isnull().sum()

movie_id    0
title       0
keywords    0
genres      0
cast        0
crew        0
overview    0
dtype: int64

In [16]:
movie.duplicated().sum()

0

In [17]:
movie.iloc[0]               #first row from the dataframe

movie_id                                                19995
title                                                  Avatar
keywords    [{"id": 1463, "name": "culture clash"}, {"id":...
genres      [{"id": 28, "name": "Action"}, {"id": 12, "nam...
cast        [{"cast_id": 242, "character": "Jake Sully", "...
crew        [{"credit_id": "52fe48009251416c750aca23", "de...
overview    In the 22nd century, a paraplegic Marine is di...
Name: 0, dtype: object

In [18]:
movie.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
^
.
.
['Action','adventure','fantasy','scifi']

In [19]:
### making a function to convert given genre into our required genre
####
###
def convert(obj):
    l = []
    for i in obj:
        l.append(i["name"])
    return l

In [20]:
# first of all i have to convert given string of list to---------> list
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
)

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [21]:
def convert(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i["name"])
    return l

In [22]:
convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
)

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

## Converting

In [23]:
movie['genres'] = movie['genres'].apply(convert)

In [24]:
movie['keywords']= movie['keywords'].apply(convert)

In [25]:
movie.head()

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca..."

In [26]:
movie['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [27]:
def top3(obj):
    cast = []
    j=0
    for i in ast.literal_eval(obj):
        cast.append(i["name"])
        j=j+1
        if j == 3:
            break
    return cast

In [28]:
top3('[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]')

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [29]:
movie['cast']= movie['cast'].apply(top3)

In [30]:
movie.head()

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca..."

In [31]:
movie['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [32]:
def director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i["job"] =='Director':
            L.append(i["name"])
            break
    return L

In [33]:
movie['crew']=movie['crew'].apply(director)

In [34]:
movie.head()

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],Following the death of District Attorney Harve...
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"John Carter is a war-weary, former military ca..."

In [35]:
##now overview is in string , so will convert in list like others

In [36]:
movie['overview']=movie['overview'].apply(lambda x: x.split())

In [37]:
movie.head()

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [38]:
 # now there is a problem that for name like 'Sam Worthington' and 'Sam Mendes' , in this there is 'Sam' in common which can confuse the model as it will treat it like same

In [39]:
movie['genres']=movie['genres'].apply(lambda x :[ i.replace(" ","") for i in x])
movie['keywords']=movie['keywords'].apply(lambda x :[ i.replace(" ","") for i in x])
movie['cast']=movie['cast'].apply(lambda x :[ i.replace(" ","") for i in x])
movie['crew']=movie['crew'].apply(lambda x :[ i.replace(" ","") for i in x])
movie['overview']=movie['overview'].apply(lambda x :[ i.replace(" ","") for i in x])

In [40]:
movie['tags']=movie['keywords']+movie['genres']+movie['cast']+movie['crew']+movie['overview']

In [41]:
movie.head()

,movie_id,title,keywords,genres,cast,crew,overview,tags
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad..."
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden..."
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p..."

In [42]:
new_movie= movie[['movie_id','title','tags']]

In [43]:
new_movie.head()

,movie_id,title,tags
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad..."
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden..."
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p..."

In [44]:
new_movie['tags']=new_movie['tags'].apply(lambda x : " ".join(x))

/var/folders/ds/g487nx0s51q5bchkc3lsw4wc0000gn/T/ipykernel_44407/1008982870.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movie['tags']=new_movie['tags'].apply(lambda x : " ".join(x))

In [45]:
new_movie.head()

,movie_id,title,tags
0,19995,Avatar,cultureclash future spacewar spacecolony socie...
1,285,Pirates of the Caribbean: At World's End,ocean drugabuse exoticisland eastindiatradingc...
2,206647,Spectre,spy basedonnovel secretagent sequel mi6 britis...
3,49026,The Dark Knight Rises,dccomics crimefighter terrorist secretidentity...
4,49529,John Carter,basedonnovel mars medallion spacetravel prince...

In [46]:
new_movie['tags'][0]

'cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver JamesCameron In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [47]:
new_movie['tags']=new_movie['tags'].apply(lambda x: x.lower())

/var/folders/ds/g487nx0s51q5bchkc3lsw4wc0000gn/T/ipykernel_44407/3764374754.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movie['tags']=new_movie['tags'].apply(lambda x: x.lower())

## Stemming

In [48]:
!pip install nltk

Requirement already satisfied: nltk in /Applications/anaconda3/lib/python3.12/site-packages (3.9.2)
Requirement already satisfied: click in /Applications/anaconda3/lib/python3.12/site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /Applications/anaconda3/lib/python3.12/site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /Applications/anaconda3/lib/python3.12/site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /Applications/anaconda3/lib/python3.12/site-packages (from nltk) (4.66.5)

In [49]:
import nltk

In [50]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [51]:
def stem(text):
    l=[]

    for i in text.split():
        l.append(ps.stem(i))

    return " ".join(l)

In [52]:
new_movie['tags']=new_movie['tags'].apply(stem)

/var/folders/ds/g487nx0s51q5bchkc3lsw4wc0000gn/T/ipykernel_44407/3244362.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movie['tags']=new_movie['tags'].apply(stem)

In [53]:
new_movie['tags'][0]

'cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav jamescameron in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization.'

In [54]:
#now we will vectorise it with the help of sklearn

In [55]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features= 5000, stop_words = 'english')

In [56]:
vectors = cv.fit_transform(new_movie['tags']).toarray()

In [57]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [58]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [59]:
 cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [60]:
from sklearn.metrics.pairwise import cosine_similarity

In [61]:
similarity = cosine_similarity(vectors)

In [62]:
similarity = similarity.astype("float32")

In [63]:
similarity.shape    #as is it calculatind cosine distance between two of vectors, here one is comaparing with 4806 and so on...

(4806, 4806)

In [64]:
similarity[0]       # comparision of first vector with own and others

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ], dtype=float32)

In [65]:
similarity[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378258, 0.        ,
       0.02615329], dtype=float32)

## final function

In [66]:
def recommend(movie):
    movie_index = new_movie[new_movie['title']==movie].index[0]      # this will find index of the user's movies
    distances = similarity[movie_index]                              # this will find similarity of user's movies to other movies
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]      # enumerate will create all data with its index in tuple format so that after sorting ccorresonding index will not lost

    for i in movies_list:
        print(new_movie.iloc[i[0]].title)                            #

In [67]:
recommend('Inception')

12 Rounds
RED
Abduction
Krrish
The Animal

In [68]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0),
 (1214, 0.28676966),
 (2405, 0.2690138),
 (3728, 0.26051304),
 (507, 0.2556086),
 (539, 0.2503867),
 (582, 0.24511108),
 (1202, 0.24455799),
 (1192, 0.23677853),
 (61, 0.23179317),
 (778, 0.23174489),
 (4046, 0.22783898),
 (1916, 0.22528177),
 (2782, 0.21853669),
 (172, 0.2123977),
 (972, 0.21086633),
 (322, 0.21052632),
 (2329, 0.20443988),
 (3606, 0.20437978),
 (260, 0.2039508),
 (151, 0.20295303),
 (4190, 0.20295303),
 (1440, 0.20277677),
 (74, 0.20246457),
 (1087, 0.20204754),
 (3671, 0.19790828),
 (577, 0.19767387),
 (973, 0.19767387),
 (47, 0.19672237),
 (2969, 0.19252141),
 (942, 0.19134595),
 (495, 0.19088542),
 (1199, 0.19088542),
 (305, 0.19007488),
 (4, 0.1892994),
 (94, 0.18731716),
 (4405, 0.18731716),
 (27, 0.18693292),
 (3325, 0.18608074),
 (1273, 0.1839418),
 (1327, 0.1839418),
 (2997, 0.18136907),
 (3997, 0.18074258),
 (83, 0.1799685),
 (1069, 0.1795462),
 (220, 0.17770466),
 (184, 0.1773431),
 (1319, 0.17699808),
 (168, 0.17521916),
 (2200, 0.17521916),
 (4336, 0.17521916),
 (931, 0.17481497),
 (36, 0.17316975),
 (373, 0.17292862),
 (300, 0.17119059),
 (3536, 0.17119059),
 (3160, 0.17040573),
 (1978, 0.16943474),
 (661, 0.16754156),
 (529, 0.1674277),
 (1827, 0.1674277),
 (91, 0.16692446),
 (41, 0.16563699),
 (67, 0.16452254),
 (150, 0.16426203),
 (1533, 0.16222142),
 (342, 0.16122924),
 (595, 0.160591),
 (31, 0.15907119),
 (2511, 0.15907119),
 (1176, 0.15789473),
 (4008, 0.1573779),
 (2727, 0.15609764),
 (149, 0.15511334),
 (838, 0.15401712),
 (26, 0.15389675),
 (187, 0.15389675),
 (1379, 0.15200838),
 (111, 0.15018785),
 (311, 0.15018785),
 (1342, 0.15018785),
 (52, 0.14843121),
 (513, 0.14843121),
 (2071, 0.14808722),
 (7, 0.14673479),
 (2756, 0.14659886),
 (127, 0.14601068),
 (579, 0.14567913),
 (581, 0.14567913),
 (108, 0.14509524),
 (466, 0.14509524),
 (1295, 0.14509524),
 (1392, 0.14421499),
 (1475, 0.14421499),
 (1353, 0.14350946),
 (1934, 0.14350946),
 (275, 0.14338483),
 (294, 0.14338483),
 (3352, 0.14338483),
 (1054, 0.14197455),
 (1271, 0.14197455),
 (490, 0.14159846),
 (1484, 0.14159846),
 (413, 0.14119563),
 (461, 0.14119563),
 (568, 0.14119563),
 (2492, 0.14119563),
 (95, 0.14048786),
 (17, 0.13977654),
 (46, 0.13910373),
 (3407, 0.13910373),
 (1961, 0.13872951),
 (56, 0.13834289),
 (249, 0.13834289),
 (1325, 0.13834289),
 (3779, 0.13834289),
 (72, 0.13710213),
 (843, 0.13710213),
 (859, 0.13710213),
 (2165, 0.13710213),
 (4538, 0.13629326),
 (476, 0.13530202),
 (505, 0.13530202),
 (668, 0.13530202),
 (935, 0.13530202),
 (3980, 0.13530202),
 (1804, 0.13518451),
 (4348, 0.13497639),
 (1320, 0.13476498),
 (158, 0.13369696),
 (502, 0.13369696),
 (777, 0.13369696),
 (126, 0.13334519),
 (1556, 0.13334519),
 (1369, 0.13245323),
 (2374, 0.13245323),
 (2580, 0.13245323),
 (4077, 0.13157895),
 (2129, 0.13124359),
 (1013, 0.12988108),
 (2177, 0.12988108),
 (3620, 0.12988108),
 (134, 0.12977713),
 (368, 0.12977713),
 (1770, 0.12977713),
 (2869, 0.12892051),
 (14, 0.12824729),
 (138, 0.12824729),
 (369, 0.12824729),
 (1084, 0.12824729),
 (2682, 0.12824729),
 (4228, 0.12824729),
 (487, 0.12725696),
 (773, 0.12725696),
 (2968, 0.12725696),
 (937, 0.12667365),
 (1737, 0.12565617),
 (2476, 0.12565617),
 (166, 0.12515654),
 (754, 0.12515654),
 (2446, 0.12515654),
 (3626, 0.12515654),
 (483, 0.12487811),
 (1094, 0.12487811),
 (1156, 0.12487811),
 (2648, 0.12487811),
 (102, 0.12462195),
 (84, 0.12361284),
 (208, 0.12262787),
 (1874, 0.12262787),
 (3374, 0.12262787),
 (438, 0.122278996),
 (557, 0.122278996),
 (1297, 0.122278996),
 (2327, 0.12166607),
 (2670, 0.12166607),
 (3081, 0.12166607),
 (139, 0.12072655),
 (68, 0.12049504),
 (781, 0.12049504),
 (1002, 0.12049504),
 (1272, 0.12049504),
 (1654, 0.12049504),
 (1000, 0.11980846),
 (549, 0.11959122),
 (870, 0.11959122),
 (900, 0.11959122),
 (3233, 0.11959122),
 (1045, 0.118469775),
 (1829, 0.118469775),
 (2056, 0.118469775),
 (2737, 0.118469775),
 (4673, 0.118469775),
 (1669, 0.118033424),
 (1711, 0.118033424),
 (2785, 0.118033424),
 (3719, 0.118033424),
 (3998, 0.118033424),
 (160, 0.11712304),
 (182, 0.11707322),
 (278, 0.11707322),
 (454, 0.11707322),
 (1613, 0.11707322),
 (2280, 0.11707322),
 (28, 0.11654331),
 (122, 0.11654331),
 (422, 0.11654331),
 (678, 0.11654331),
 (589, 0.11633501),
 (2543, 0.11587244),
 (1493, 0.11551285),
 (3210, 0.11506355),
 (189, 0.114707865),
 (236, 0.114707865),
 (1218, 0.114707865),
 (1299, 0.114707865),
 (85, 0.11412706),
 (432, 0.113577716),
 (1414, 0.113577716),
 (50, 0.1129565),
 (1612, 0.1129565),
 (123, 0.11248032),
 (420, 0.11248032),
 (536, 0.11248032),
 (889, 0.1124362),
 (3145, 0.112390295),
 (256, 0.11164844),
 (808, 0.11164844),
 (1346, 0.11164844),
 (1571, 0.11164844),
 (1508, 0.11141413),
 (2368, 0.11141413),
 (3307, 0.11141413),
 (87, 0.111282974),
 (121, 0.111282974),
 (232, 0.111282974),
 (4468, 0.111282974),
 (206, 0.11092108),
 (238, 0.11092108),
 (228, 0.1103777),
 (81, 0.11020775),
 (1570, 0.11020775),
 (21, 0.109681696),
 (449, 0.109681696),
 (1029, 0.109681696),
 (1941, 0.109681696),
 (2144, 0.109681696),
 (3006, 0.109681696),
 (3426, 0.109681696),
 (692, 0.10936966),
 (200, 0.10882144),
 (627, 0.10882144),
 (653, 0.10882144),
 (1520, 0.10882144),
 (307, 0.10876596),
 (5, 0.108388744),
 (740, 0.108388744),
 (3091, 0.108388744),
 (3628, 0.108388744),
 (786, 0.10814761),
 (3496, 0.10814761),
 (4777, 0.10814761),
 (229, 0.10748615),
 (572, 0.10743376),
 (939, 0.106836684),
 (332, 0.10667615),
 (472, 0.10667615),
 (1235, 0.10667615),
 (170, 0.10650358),
 (262, 0.10650358),
 (1164, 0.10619885),
 (1497, 0.10619885),
 (1741, 0.10619885),
 (2157, 0.10619885),
 (2630, 0.10619885),
 (4133, 0.10619885),
 (467, 0.10559715),
 (541, 0.10559715),
 (1492, 0.10559715),
 (131, 0.10526316),
 (295, 0.10526316),
 (2068, 0.10526316),
 (3338, 0.10526316),
 (2494, 0.10471348),
 (75, 0.103904866),
 (223, 0.103904866),
 (687, 0.103904866),
 (814, 0.103904866),
 (1193, 0.103904866),
 (1767, 0.103904866),
 (2813, 0.103904866),
 (654, 0.103851624),
 (2435, 0.103851624),
 (105, 0.10375717),
 (233, 0.10375717),
 (624, 0.10375717),
 (2319, 0.10375717),
 (2452, 0.10375717),
 (2517, 0.10375717),
 (3053, 0.10375717),
 (3619, 0.10375717),
 (3837, 0.10375717),
 (1451, 0.10301071),
 (10, 0.10259783),
 (1080, 0.10259783),
 (3150, 0.10259783),
 (3632, 0.10259783),
 (3753, 0.10259783),
 (3872, 0.10259783),
 (4095, 0.10259783),
 (2102, 0.10218989),
 (2758, 0.10147651),
 (3659, 0.10147651),
 (3952, 0.10147651),
 (3439, 0.10138839),
 (508, 0.101338916),
 (1292, 0.101338916),
 (2243, 0.101338916),
 (1401, 0.10060546),
 (1435, 0.10060546),
 (2095, 0.10060546),
 (312, 0.10012524),
 (330, 0.10012524),
 (643, 0.10012524),
 (986, 0.10012524),
 (1035, 0.10012524),
 (1610, 0.10012524),
 (35, 0.099339925),
 (157, 0.099339925),
 (319, 0.099339925),
 (325, 0.099339925),
 (715, 0.099339925),
 (1075, 0.099339925),
 (1278, 0.099339925),
 (1880, 0.099339925),
 (2049, 0.099339925),
 (4016, 0.099339925),
 (4196, 0.099339925),
 (4490, 0.099339925),
 (363, 0.099092506),
 (491, 0.099092506),
 (266, 0.09895414),
 (445, 0.09895414),
 (510, 0.09895414),
 (3618, 0.09895414),
 (3781, 0.09895414),
 (3933, 0.09895414),
 (1771, 0.09836119),
 (410, 0.097823195),
 (480, 0.097823195),
 (535, 0.097823195),
 (898, 0.097823195),
 (1107, 0.097823195),
 (1397, 0.097823195),
 (1819, 0.097823195),
 (2249, 0.097823195),
 (33, 0.09733285),
 (148, 0.09733285),
 (263, 0.09733285),
 (878, 0.09733285),
 (1154, 0.09733285),
 (1723, 0.09733285),
 (1938, 0.09733285),
 (2783, 0.09733285),
 (4254, 0.09733285),
 (4403, 0.09733285),
 (4472, 0.09733285),
 (9, 0.096730165),
 (334, 0.096730165),
 (371, 0.09567297),
 (412, 0.09567297),
 (2237, 0.09567297),
 (2552, 0.09567297),
 (4545, 0.09558989),
 (362, 0.09544271),
 (791, 0.09544271),
 (1569, 0.09544271),
 (2558, 0.09544271),
 (4201, 0.09544271),
 (18, 0.09493291),
 (11, 0.0946497),
 (587, 0.0946497),
 (301, 0.09365858),
 (660, 0.09365858),
 (920, 0.09365858),
 (978, 0.09365858),
 (1274, 0.09365858),
 (1355, 0.09365858),
 (1470, 0.09365858),
 (1682, 0.09365858),
 (1688, 0.09365858),
 (1717, 0.09365858),
 (2392, 0.09365858),
 (2484, 0.09365858),
 (2588, 0.09365858),
 (2641, 0.09365858),
 (2646, 0.09365858),
 (2816, 0.09365858),
 (3535, 0.09365858),
 (3718, 0.09365858),
 (4331, 0.09365858),
 (4502, 0.09365858),
 (129, 0.092697956),
 (243, 0.092697956),
 (279, 0.092697956),
 (473, 0.092697956),
 (596, 0.092697956),
 (813, 0.092697956),
 (1442, 0.092697956),
 (1697, 0.092697956),
 (3405, 0.092697956),
 (785, 0.092434235),
 (219, 0.0919709),
 (244, 0.0919709),
 (511, 0.0919709),
 (1752, 0.0919709),
 (2089, 0.0919709),
 (2647, 0.0919709),
 (3734, 0.0919709),
 (230, 0.0918398),
 (799, 0.0918398),
 (239, 0.09125668),
 (2566, 0.09125668),
 (43, 0.09086217),
 (602, 0.09086217),
 (995, 0.09086217),
 (1231, 0.09086217),
 (1842, 0.09086217),
 (3879, 0.09086217),
 (12, 0.09037129),
 (88, 0.09037129),
 (167, 0.09037129),
 (356, 0.09037129),
 (400, 0.09037129),
 (1304, 0.09037129),
 (1476, 0.09037129),
 (2247, 0.09037129),
 (2955, 0.09037129),
 (331, 0.08998425),
 (2359, 0.08998425),
 (2792, 0.08998425),
 (2852, 0.08998425),
 (3387, 0.08998425),
 (3441, 0.08998425),
 (3460, 0.08998425),
 (4343, 0.08998425),
 (4353, 0.08998425),
 (274, 0.0897731),
 (1902, 0.0891313),
 (2111, 0.08903057),
 (292, 0.08885233),
 (564, 0.08885233),
 (1025, 0.08885233),
 (2656, 0.08885233),
 (2864, 0.08885233),
 (3320, 0.08885233),
 (169, 0.08830216),
 (270, 0.08830216),
 (618, 0.08830216),
 (1779, 0.08830216),
 (2105, 0.08830216),
 (2709, 0.08830216),
 (2736, 0.08830216),
 (3551, 0.08830216),
 (479, 0.08797692),
 (752, 0.08749573),
 (1828, 0.08749573),
 (2444, 0.08746393),
 (23, 0.087407485),
 (141, 0.087407485),
 (389, 0.087407485),
 (745, 0.087407485),
 (794, 0.087407485),
 (960, 0.087407485),
 (1247, 0.087407485),
 (1257, 0.087407485),
 (3446, 0.087407485),
 (3447, 0.087407485),
 (143, 0.086711),
 (199, 0.086711),
 (827, 0.086711),
 (1526, 0.086711),
 (2876, 0.086711),
 (3554, 0.086711),
 (4516, 0.086711),
 (4587, 0.086711),
 (2, 0.0860309),
 (457, 0.0860309),
 (775, 0.0860309),
 (1374, 0.0860309),
 (2579, 0.0860309),
 (3133, 0.0860309),
 (4754, 0.0860309),
 (234, 0.08594701),
 (1017, 0.08594701),
 (2350, 0.08594701),
 (32, 0.085202865),
 (217, 0.085202865),
 (142, 0.08471737),
 (894, 0.08471737),
 (1095, 0.08471737),
 (1140, 0.08471737),
 (1585, 0.08471737),
 (2300, 0.08471737),
 (4560, 0.08471737),
 (48, 0.08447772),
 (190, 0.08447772),
 (1303, 0.08447772),
 (1635, 0.08447772),
 (2966, 0.08447772),
 (62, 0.08377078),
 (381, 0.08377078),
 (534, 0.08377078),
 (1694, 0.08377078),
 (3178, 0.08377078),
 (3216, 0.08377078),
 (3976, 0.08377078),
 (4737, 0.08377078),
 (1, 0.08346223),
 (152, 0.08346223),
 (203, 0.08346223),
 (315, 0.08346223),
 (547, 0.08346223),
 (1684, 0.08346223),
 (2124, 0.08346223),
 (2382, 0.08321783),
 (19, 0.0830813),
 (403, 0.0830813),
 (3903, 0.0830813),
 (45, 0.08240856),
 (2199, 0.08240856),
 (39, 0.08226127),
 (227, 0.08226127),
 (341, 0.08226127),
 (626, 0.08226127),
 (787, 0.08226127),
 (1205, 0.08226127),
 (1745, 0.08226127),
 (2163, 0.08226127),
 (2657, 0.08226127),
 (3138, 0.08226127),
 (3299, 0.08226127),
 (3468, 0.08226127),
 (63, 0.08175191),
 (501, 0.08175191),
 (38, 0.08111071),
 (242, 0.08111071),
 (245, 0.08111071),
 (306, 0.08111071),
 (584, 0.08111071),
 (812, 0.08111071),
 (866, 0.08111071),
 (901, 0.08111071),
 (1267, 0.08111071),
 (1515, 0.08111071),
 (1660, 0.08111071),
 (2335, 0.08111071),
 (2640, 0.08111071),
 (2667, 0.08111071),
 (2861, 0.08111071),
 (2873, 0.08111071),
 (3525, 0.08111071),
 (3924, 0.08111071),
 (4492, 0.08111071),
 (4568, 0.08111071),
 (4626, 0.08111071),
 (4641, 0.08111071),
 (4654, 0.08111071),
 (4657, 0.08111071),
 (51, 0.08048436),
 (164, 0.08000711),
 (854, 0.08000711),
 (899, 0.08000711),
 (1323, 0.08000711),
 (1743, 0.08000711),
 (2679, 0.08000711),
 (3762, 0.08000711),
 (3814, 0.08000711),
 (3849, 0.08000711),
 (486, 0.07992076),
 (103, 0.0798723),
 (222, 0.0798723),
 (1530, 0.0798723),
 (2788, 0.0798723),
 (4506, 0.0798723),
 (1894, 0.079274006),
 (16, 0.078947365),
 (37, 0.078947365),
 (241, 0.078947365),
 (329, 0.078947365),
 (1078, 0.078947365),
 (1159, 0.078947365),
 (2291, 0.078947365),
 (3231, 0.078947365),
 (4316, 0.078947365),
 (193, 0.07878169),
 (153, 0.07868895),
 (776, 0.07868895),
 (1043, 0.07868895),
 (1824, 0.07868895),
 (1922, 0.07868895),
 (3726, 0.07868895),
 (3830, 0.07868895),
 (4279, 0.07868895),
 (4473, 0.07868895),
 (125, 0.078433044),
 (286, 0.078116655),
 (1655, 0.078116655),
 (174, 0.07792865),
 (402, 0.07792865),
 (922, 0.07792865),
 (1111, 0.07792865),
 (2936, 0.07792865),
 (3026, 0.07792865),
 (3089, 0.07792865),
 (3100, 0.07792865),
 (3162, 0.07792865),
 (4341, 0.07792865),
 (1920, 0.07755667),
 (3558, 0.07755667),
 (1280, 0.07700856),
 (40, 0.076948375),
 (96, 0.076948375),
 (101, 0.076948375),
 (112, 0.076948375),
 (207, 0.076948375),
 (632, 0.076948375),
 (737, 0.076948375),
 (1287, 0.076948375),
 (2215, 0.076948375),
 (4266, 0.076948375),
 (4624, 0.076948375),
 (850, 0.07647191),
 (1003, 0.07647191),
 (1137, 0.07647191),
 (1252, 0.07647191),
 (1617, 0.07647191),
 (2161, 0.07647191),
 (2270, 0.07647191),
 (2708, 0.07647191),
 (3428, 0.07647191),
 (4163, 0.07647191),
 (70, 0.07600419),
 (82, 0.07600419),
 (235, 0.07600419),
 (349, 0.07600419),
 (492, 0.07600419),
 (1288, 0.07600419),
 (1519, 0.07600419),
 (2445, 0.07600419),
 (2914, 0.07600419),
 (4558, 0.07600419),
 (246, 0.07594632),
 (2001, 0.07543143),
 (3329, 0.0753094),
 (98, 0.075093925),
 (210, 0.075093925),
 (361, 0.075093925),
 (365, 0.075093925),
 (503, 0.075093925),
 (540, 0.075093925),
 (680, 0.075093925),
 (1007, 0.075093925),
 (1291, 0.075093925),
 (2159, 0.075093925),
 (4043, 0.075093925),
 (4203, 0.075093925),
 (2252, 0.07492687),
 (205, 0.07443229),
 (800, 0.07443229),
 (993, 0.07443229),
 (1321, 0.07443229),
 (1517, 0.07443229),
 (1766, 0.07443229),
 (2322, 0.07443229),
 (2547, 0.07443229),
 (2797, 0.07443229),
 (3067, 0.07443229),
 (3115, 0.07443229),
 (3124, 0.07443229),
 (4009, 0.07443229),
 (4412, 0.07443229),
 (4542, 0.07443229),
 (634, 0.074215606),
 (885, 0.074215606),
 (1068, 0.074215606),
 (2391, 0.074215606),
 (3699, 0.074215606),
 (1986, 0.073947385),
 (2186, 0.073947385),
 (3429, 0.073947385),
 (3, 0.07347184),
 (1483, 0.07347184),
 (71, 0.073367395),
 (908, 0.073367395),
 (1363, 0.073367395),
 (1619, 0.073367395),
 (2017, 0.073367395),
 (2052, 0.073367395),
 (3020, 0.073367395),
 (3283, 0.073367395),
 (3803, 0.073367395),
 (59, 0.07254762),
 (179, 0.07254762),
 (728, 0.07254762),
 (833, 0.07254762),
 (977, 0.07254762),
 (1485, 0.07254762),
 (1651, 0.07254762),
 (1761, 0.07254762),
 (1992, 0.07254762),
 (2110, 0.07254762),
 (2208, 0.07254762),
 (2293, 0.07254762),
 (2313, 0.07254762),
 (2377, 0.07254762),
 (2475, 0.07254762),
 (2768, 0.07254762),
 (2986, 0.07254762),
 (3070, 0.07254762),
 (3101, 0.07254762),
 (3153, 0.07254762),
 (3253, 0.07254762),
 (3353, 0.07254762),
 (3481, 0.07254762),
 (3714, 0.07254762),
 (3974, 0.07254762),
 (4431, 0.07254762),
 (4443, 0.07254762),
 (4640, 0.07254762),
 (790, 0.07209841),
 (1955, 0.07209841),
 (76, 0.07175473),
 (784, 0.07175473),
 (932, 0.07175473),
 (933, 0.07175473),
 (1166, 0.07175473),
 (1879, 0.07175473),
 (2697, 0.07175473),
 (2848, 0.07175473),
 (2901, 0.07175473),
 (3303, 0.07175473),
 (3421, 0.07175473),
 (3462, 0.07175473),
 (4081, 0.07175473),
 (86, 0.07098728),
 (93, 0.07098728),
 (175, 0.07098728),
 (271, 0.07098728),
 (543, 0.07098728),
 (674, 0.07098728),
 (1143, 0.07098728),
 (1338, 0.07098728),
 (2827, 0.07098728),
 (3204, 0.07098728),
 (3609, 0.07098728),
 (4483, 0.07098728),
 (1238, 0.07079923),
 (1406, 0.07079923),
 (2441, 0.07079923),
 (2759, 0.07079923),
 (2850, 0.07079923),
 (3221, 0.07079923),
 (4638, 0.07079923),
 (55, 0.07038154),
 (183, 0.07038154),
 (1628, 0.07024393),
 (1843, 0.07024393),
 (3483, 0.07024393),
 (97, 0.06952347),
 (254, 0.06952347),
 (302, 0.06952347),
 (782, 0.06952347),
 (1144, 0.06952347),
 (1453, 0.06952347),
 (2099, 0.06952347),
 (3298, 0.06952347),
 (3905, 0.06952347),
 (4178, 0.06952347),
 (336, 0.06917144),
 (1733, 0.06917144),
 (2529, 0.06917144),
 (3889, 0.06917144),
 (4290, 0.06917144),
 (419, 0.06882472),
 (600, 0.06882472),
 (1276, 0.06882472),
 (1998, 0.06882472),
 (2014, 0.06882472),
 (2205, 0.06882472),
 (2239, 0.06882472),
 (665, 0.06814663),
 (671, 0.06814663),
 (704, 0.06814663),
 (732, 0.06814663),
 (1534, 0.06814663),
 (2031, 0.06814663),
 (3018, 0.06814663),
 (3308, 0.06814663),
 (3586, 0.06814663),
 (4121, 0.06814663),
 (4392, 0.06814663),
 (100, 0.06765101),
 (209, 0.06765101),
 (308, 0.06765101),
 (498, 0.06765101),
 (537, 0.06765101),
 (570, 0.06765101),
 (1290, 0.06765101),
 (1462, 0.06765101),
 (1856, 0.06765101),
 (2214, 0.06765101),
 (2431, 0.06765101),
 (2618, 0.06765101),
 (2660, 0.06765101),
 (2739, 0.06765101),
 (3396, 0.06765101),
 (3674, 0.06765101),
 (4214, 0.06765101),
 (58, 0.06748819),
 (124, 0.06748819),
 (1441, 0.06748819),
 (2301, 0.06748819),
 (3223, 0.06748819),
 (3908, 0.06748819),
 (1630, 0.06728631),
 (30, 0.06684848),
 (734, 0.06684848),
 (735, 0.06684848),
 (3877, 0.06684848),
 (488, 0.06657427),
 (22, 0.06622662),
 (212, 0.06622662),
 (215, 0.06622662),
 (237, 0.06622662),
 (604, 0.06622662),
 (635, 0.06622662),
 (695, 0.06622662),
 (1016, 0.06622662),
 (1083, 0.06622662),
 (1085, 0.06622662),
 (1119, 0.06622662),
 (1169, 0.06622662),
 (1377, 0.06622662),
 (1428, 0.06622662),
 (2246, 0.06622662),
 (2255, 0.06622662),
 (2298, 0.06622662),
 (2316, 0.06622662),
 (2653, 0.06622662),
 (2888, 0.06622662),
 (2974, 0.06622662),
 (3239, 0.06622662),
 (3410, 0.06622662),
 (3992, 0.06622662),
 (4059, 0.06622662),
 (4351, 0.06622662),
 (304, 0.065789476),
 (1173, 0.06562179),
 (1999, 0.06562179),
 (2131, 0.06562179),
 (2400, 0.06562179),
 (2592, 0.06562179),
 (3388, 0.06562179),
 (3633, 0.06562179),
 (4017, 0.065547355),
 (2828, 0.06521547),
 (29, 0.06503325),
 (281, 0.06503325),
 (1527, 0.06503325),
 (2048, 0.06503325),
 (3820, 0.06503325),
 (109, 0.06488857),
 (216, 0.06488857),
 (267, 0.06488857),
 (621, 0.06488857),
 (744, 0.06488857),
 (1066, 0.06488857),
 (1074, 0.06488857),
 (1434, 0.06488857),
 (1482, 0.06488857),
 (2264, 0.06488857),
 (2266, 0.06488857),
 (2305, 0.06488857),
 (2575, 0.06488857),
 (2711, 0.06488857),
 (2880, 0.06488857),
 (3179, 0.06488857),
 (3372, 0.06488857),
 (3570, 0.06488857),
 (3899, 0.06488857),
 (3927, 0.06488857),
 (4623, 0.06488857),
 (447, 0.064460255),
 (746, 0.064460255),
 (1009, 0.064460255),
 (1844, 0.064460255),
 (3172, 0.064460255),
 (2515, 0.064249255),
 (425, 0.06390215),
 (443, 0.06390215),
 (471, 0.06390215),
 (1975, 0.06390215),
 (2260, 0.06390215),
 (2523, 0.06390215),
 (159, 0.06362848),
 (290, 0.06362848),
 (546, 0.06362848),
 (951, 0.06362848),
 (1260, 0.06362848),
 (1302, 0.06362848),
 (1703, 0.06362848),
 (1850, 0.06362848),
 (1946, 0.06362848),
 (2109, 0.06362848),
 (2224, 0.06362848),
 (3116, 0.06362848),
 (3131, 0.06362848),
 (3251, 0.06362848),
 (3929, 0.06362848),
 (4004, 0.06362848),
 (4271, 0.06362848),
 (4312, 0.06362848),
 (4355, 0.06362848),
 (4704, 0.06362848),
 (612, 0.06335829),
 (1091, 0.06335829),
 (1458, 0.06335829),
 (3342, 0.06335829),
 (3738, 0.06335829),
 (15, 0.06282809),
 (253, 0.06282809),
 (591, 0.06282809),
 (2315, 0.06282809),
 (3296, 0.06282809),
 (3605, 0.06282809),
 (276, 0.062439054),
 (309, 0.062439054),
 (957, 0.062439054),
 (1601, 0.062439054),
 (1602, 0.062439054),
 (1940, 0.062439054),
 (2596, 0.062439054),
 (2946, 0.062439054),
 (3832, 0.062439054),
 (4357, 0.062439054),
 (79, 0.062310975),
 (92, 0.062310975),
 (106, 0.062310975),
 (963, 0.062310975),
 (1028, 0.062310975),
 (1189, 0.062310975),
 (1200, 0.062310975),
 (2516, 0.062310975),
 (2886, 0.062310975),
 (107, 0.06180642),
 (836, 0.06180642),
 (3076, 0.06180642),
 (90, 0.061313935),
 (154, 0.061313935),
 (259, 0.061313935),
 (348, 0.061313935),
 (375, 0.061313935),
 (404, 0.061313935),
 (615, 0.061313935),
 (733, 0.061313935),
 (768, 0.061313935),
 (863, 0.061313935),
 (945, 0.061313935),
 (1101, 0.061313935),

In [69]:
import pickle

In [70]:
pickle.dump(new_movie.to_dict(),open('movies_dict.pkl','wb'))

In [71]:
pickle.dump(similarity,open('similarity.pkl','wb'))